name: "examples"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: say hello
        run: echo "hello world"

      - name: run tests
        run: echo "running tests...."

      - name: info
        run: |
          echo $GITHUB_RUN_ID 
          echo $GITHUB_RUN_NUMBER
          # echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ccmpb/experiments/pulls/1/reviews \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --fail

            curl -L \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/ccmpb/experiments/actions/runs/710869213/logs" \
              --header 'authorization: Bearer ${{ secrets.ACTION_PAT }}' \
              --fail > runlog.zip 
            # -H "Accept: application/vnd.github.v3+json" \
            # https://api.github.com/repos/octocat/hello-world/pulls/42/reviews

      - name: compliance 
        uses: actions/upload-artifact@v1.0.0
        with:
          name: runlog.zip 
          path: runlog.zip 

          # date > generated.txt
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git add .
          # git commit -m "generated"
          # git push
