name: "examples"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v2
      - name: say hello
        run: echo "hello world"

      - name: run tests
        run: echo "running tests...."

      - name: info
        run: |
          echo "$GITHUB_RUN_ID"
          echo "$GITHUB_RUN_NUMBER"
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"

          MERGE_SHA=25537ed9e29af322bba3374e1d9d18bc98380da7
          # echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          # curl \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   https://api.github.com/repos/ccmpb/experiments/pulls/1/reviews \
          #   --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          #   --fail
          #
          # curl -vL \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   --url "https://api.github.com/repos/ccmpb/experiments/actions/runs/$GITHUB_RUN_ID/logs" \
          #   --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          #   --fail > runlog.zip 

            curl \
              -H "Accept: application/vnd.github.v3+json" \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --url "https://api.github.com/search/issues?q=$MERGE_SHA+repo:ccmpb/experiments+type:pr" \
              --fail

            # -H "Accept: application/vnd.github.v3+json" \
            # https://api.github.com/repos/octocat/hello-world/pulls/42/reviews

      # - name: compliance 
      #   uses: actions/upload-artifact@v1.0.0
      #   with:
      #     name: runlog.zip 
      #     path: runlog.zip 

          # date > generated.txt
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git add .
          # git commit -m "generated"
          # git push
